#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1
PROG="/root/puli_gps_mqtt.sh"
LOG_TAG="puli_gps"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh $PROG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_set_param respawn_limit 10 60
    procd_close_instance
}

stop_service() {
    return 0
}
